# Development Environment Configuration for Task Service

[service]
name = "tyl-task-service"
version = "1.0.0"

[api]
host = "0.0.0.0"
port = 3000
request_timeout_ms = 30000
max_request_size = 1048576

# FalkorDB configuration
[falkordb]
host = "falkordb"
port = 6379
password = "taskservice123"
database = 0
graph_name = "task_management"
max_connections = 10
timeout_seconds = 5

# Redis for pub/sub
[redis_pubsub]
host = "redis-pubsub"
port = 6379
password = "pubsub123"
max_connections = 10
timeout_seconds = 5

[external]
timeout_ms = 10000
retry_attempts = 3
retry_delay_ms = 1000

[monitoring]
metrics_enabled = true
tracing_enabled = true
health_check_enabled = true

# Development-specific settings
[logging]
level = "debug"
format = "pretty"

[cors]
allowed_origins = ["http://localhost:3000", "http://localhost:8080"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
allowed_headers = ["content-type", "authorization", "x-correlation-id"]

# Task service specific configuration
[task_service]
max_tasks_per_user = 20
max_subtask_depth = 5
default_task_priority = "medium"
auto_assign_on_create = false
enable_analytics = true

# Event configuration
[events]
enabled = true
batch_size = 100
flush_interval_ms = 1000
retry_attempts = 3