# Development Environment Configuration

[service]
name = "tyl-{microservice-name}"
version = "1.0.0"

[api]
host = "127.0.0.1"
port = 3000
request_timeout_ms = 30000
max_request_size = 1048576

[database]
# Uncomment and configure for your database
# url = "postgres://dev_user:dev_pass@localhost:5432/dev_db"
# max_connections = 5
# connection_timeout_ms = 5000
# query_timeout_ms = 10000

[external]
timeout_ms = 10000
retry_attempts = 3
retry_delay_ms = 1000

[monitoring]
metrics_enabled = true
tracing_enabled = true
health_check_enabled = true

# Development-specific settings
[logging]
level = "debug"
format = "pretty"

[cors]
allowed_origins = ["http://localhost:3000", "http://localhost:8080"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["content-type", "authorization", "x-correlation-id"]